import './App.css'; 
import Button from './components/Button.jsx';
import Modal from './components/Modal.jsx';
import Tooltip from './components/Tooltip.jsx';
import Table from './components/Table.jsx';
import DarkModeToggle from './components/DarkModeToggle.jsx';
import LoadingSpinnerWithStyle from './components/LoadingSpinner.jsx';
import Card from './components/Card.jsx';
import Dropdown from './components/Dropdown.jsx';
import Accordion from './components/Accordion.jsx';
import Tabs from './components/Tabs.jsx';
import Input from './components/Input.jsx';
import Badge from './components/Badge.jsx';
import Alert from './components/Alert.jsx';
import SpinningCube from './components/SpinningCube.jsx';
import Scene3D from './components/Scene.jsx';
import WaveDeformedPlane from './components/WaveDeformedPlane.jsx';
import CubeWithMouse from './components/CubeWithMouse.jsx';
import ColorSphere from './components/ColorSphere.jsx';
import BouncingBallsScene from './components/BouncingBalls.jsx';
import RotatingEarth from './components/RotatingEarth.jsx';
import Donut from './components/Donut.jsx';
import WaveyImage from './components/WaveyImage.jsx';
import RubiksCubeScene from './components/RubicsCube.jsx';
//exporting all the components
export  {Button ,Scene3D,Modal,Tooltip,Table,DarkModeToggle,LoadingSpinnerWithStyle,SpinningCube,Card,Dropdown,Accordion,Tabs,Input,Badge,Alert,WaveDeformedPlane,CubeWithMouse,ColorSphere,RotatingEarth,Donut,BouncingBallsScene,WaveyImage,RubiksCubeScene};